# Generated by Django 3.2.9 on 2021-11-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='theatre_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.theatre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('', 'Language'), ('English', 'English'), ('Hindi', 'Hindi'), ('KANNADA', 'KANNADA')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('', 'Payment mode'), ('upi', 'UPI'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('', 'Seating'), ('classic', 'Classic'), ('premium', 'Premium')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='screenseat',
            name='type',
            field=models.CharField(choices=[('', 'Seating'), ('classic', 'Classic'), ('premium', 'Premium')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='showseat',
            name='type',
            field=models.CharField(choices=[('', 'Seating'), ('classic', 'Classic'), ('premium', 'Premium')], max_length=50, null=True),
        ),
    ]
