# Generated by Django 3.2.9 on 2021-11-27 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20211127_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showseat',
            name='booking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.booking'),
        ),
    ]
